import sys
import argparse
import asyncio
import subprocess
from pathlib import Path

# Setup paths
ROOT_DIR = Path(__file__).resolve().parent
sys.path.append(str(ROOT_DIR))

from log import get_logger
from src.ingestion import process_video_input
from src.transcription import transcribe_audio
from src.ai_logic import analyze_transcript
from src.video_editor import cut_and_save_reels, create_highlights_video

logger = get_logger("MainPipeline")

def run_pipeline(source: str):
    logger.info("="*50)
    logger.info(f"🚀 Starting Autonomous Video Processing Pipeline")
    logger.info(f"Source: {source}")
    logger.info("="*50)
    
    try:
        # Step 1: Ingestion
        logger.info("\n[STEP 1/4] Ingesting Video & Extracting Audio...")
        video_path, audio_path = process_video_input(source)
        
        output_dir = ROOT_DIR / "data" / "output"
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Step 1.5: Apply noise cancellation + branding logo overlay to the full original video
        logger.info("\n[STEP 1.5] Creating noise-cancelled + branded original video...")
        denoised_video_path = output_dir / f"{Path(video_path).stem}_denoised.mp4"
        logo_path = ROOT_DIR / "logo" / "branding.jpeg"
        
        if logo_path.exists():
            # Use filter_complex to overlay logo on top-right while also denoising audio
            cmd = [
                "ffmpeg", "-y",
                "-i", video_path,
                "-i", str(logo_path),
                "-filter_complex",
                # Scale logo to 10% of video height, place at top-right with 20px padding
                "[1:v]scale=-1:ih*0.1[logo];[0:v][logo]overlay=W-w-20:20[vout]",
                "-map", "[vout]",
                "-map", "0:a",
                "-af", "afftdn=nf=-25",   # same noise floor as ingestion.py
                "-c:v", "libx264",
                "-preset", "fast",
                "-c:a", "aac",
                "-b:a", "192k",
                str(denoised_video_path)
            ]
        else:
            logger.warning("Logo file not found, creating denoised video without watermark.")
            cmd = [
                "ffmpeg", "-y",
                "-i", video_path,
                "-c:v", "copy",
                "-af", "afftdn=nf=-25",
                "-c:a", "aac",
                "-b:a", "192k",
                str(denoised_video_path)
            ]
        try:
            subprocess.run(cmd, capture_output=True, check=True)
            logger.info(f"Noise-cancelled + branded original video saved to: {denoised_video_path}")
            # Use this denoised+branded video for the rest of the pipeline
            video_path = str(denoised_video_path)
        except Exception as e:
            logger.warning(f"Failed to create denoised video, continuing with original: {e}")
        
        # Step 2: Transcription
        logger.info("\n[STEP 2/4] Transcribing Audio with Whisper...")
        transcript_segments = transcribe_audio(audio_path)
        if not transcript_segments:
            logger.error("No transcript generated. Aborting pipeline.")
            return
            
        # Step 3: AI Analysis
        logger.info("\n[STEP 3/4] Analyzing Transcript with LLM...")
        ai_analysis = asyncio.run(analyze_transcript(transcript_segments))
        
        # Print the text summary to the console
        logger.info(f"\n📝 Video Summary Generated by AI:\n{ai_analysis.get('summary', 'No summary generated.')}\n")
        
        # Step 3.5: Save an article based on the AI analysis
        logger.info("\n[STEP 3.5] Generating Article using AI...")
        from src.article_generator import generate_article_from_json
        article_path = output_dir / f"{Path(video_path).stem}_article.md"
        try:
            asyncio.run(generate_article_from_json(ai_analysis, str(article_path)))
        except Exception as e:
            logger.warning(f"Failed to generate and save article: {e}")
        
        # Step 4: Video Editing
        logger.info("\n[STEP 4/4] Cutting Reels and Highlights...")
        reels_data = ai_analysis.get('reels', [])
        hl_data = ai_analysis.get('highlight_segments', [])
        
        if reels_data:
            cut_and_save_reels(video_path, reels_data)
        else:
            logger.warning("No reels generated by AI.")
            
        if hl_data:
            hl_result = create_highlights_video(video_path, hl_data)
            logger.info(f"Highlights MP4: {hl_result.get('mp4', '')} | MP3: {hl_result.get('mp3', '')}")
        else:
            logger.warning("No highlights generated by AI.")
            
        logger.info("\n🎉 Pipeline Completed Successfully! Check the data/output folder.")
        logger.info("="*50)
        
    except Exception as e:
        logger.error(f"❌ Pipeline failed: {str(e)}", exc_info=True)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Autonomous Video Extraction and Summarization AI")
    parser.add_argument(
        "source", 
        help="Provide a YouTube URL or a path to a local MP4 file to process"
    )
    
    args = parser.parse_args()
    run_pipeline(args.source)
