import sys
import argparse
import asyncio
from pathlib import Path

# Setup paths
ROOT_DIR = Path(__file__).resolve().parent
sys.path.append(str(ROOT_DIR))

from log import get_logger
from src.ingestion import process_video_input
from src.transcription import transcribe_audio
from src.ai_logic import analyze_transcript
from src.video_editor import cut_and_save_reels, create_highlights_video

logger = get_logger("MainPipeline")

def run_pipeline(source: str):
    logger.info("="*50)
    logger.info(f"🚀 Starting Autonomous Video Processing Pipeline")
    logger.info(f"Source: {source}")
    logger.info("="*50)
    
    try:
        # Step 1: Ingestion
        logger.info("\n[STEP 1/4] Ingesting Video & Extracting Audio...")
        video_path, audio_path = process_video_input(source)
        
        # Step 2: Transcription
        logger.info("\n[STEP 2/4] Transcribing Audio with Whisper...")
        transcript_segments = transcribe_audio(audio_path)
        if not transcript_segments:
            logger.error("No transcript generated. Aborting pipeline.")
            return
            
        # Step 3: AI Analysis
        logger.info("\n[STEP 3/4] Analyzing Transcript with LLM...")
        ai_analysis = asyncio.run(analyze_transcript(transcript_segments))
        
        # Print the text summary to the console
        logger.info(f"\n📝 Video Summary Generated by AI:\n{ai_analysis.get('summary', 'No summary generated.')}\n")
        
        # Step 4: Video Editing
        logger.info("\n[STEP 4/4] Cutting Reels and Highlights...")
        reels_data = ai_analysis.get('reels', [])
        hl_data = ai_analysis.get('highlight_segments', [])
        
        if reels_data:
            cut_and_save_reels(video_path, reels_data)
        else:
            logger.warning("No reels generated by AI.")
            
        if hl_data:
            create_highlights_video(video_path, hl_data)
        else:
            logger.warning("No highlights generated by AI.")
            
        logger.info("\n🎉 Pipeline Completed Successfully! Check the data/output folder.")
        logger.info("="*50)
        
    except Exception as e:
        logger.error(f"❌ Pipeline failed: {str(e)}", exc_info=True)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Autonomous Video Extraction and Summarization AI")
    parser.add_argument(
        "source", 
        help="Provide a YouTube URL or a path to a local MP4 file to process"
    )
    
    args = parser.parse_args()
    run_pipeline(args.source)
